name: Backend CI/CD to AKS

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backendCICD.yml'
      - 'k8s-manifests/backend-deployment.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_CONTAINER_REGISTRY: acrk8svithu.azurecr.io
      IMAGE_NAME: backend-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Azure
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az aks get-credentials --resource-group my-rg --name my-aks
            kubectl apply -f k8s-manifests/backend-deployment.yaml


      - name: Log in to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: acrk8svithu.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }} ./backend

      - name: Push Docker Image to ACR
        run: |
          docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Set up Kubernetes
        uses: azure/aks-set-context@v3
        with:
          cluster-name: aks-k8svithu
          resource-group: rg-k8s-microservices


      - name: Deploy Backend to AKS
        run: |
          kubectl set image deployment/backend-deployment backend=$AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }}
