name: Build and Deploy to AKS

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: acrk8svithu.azurecr.io
        username: ${{ secrets.AZURE_CREDENTIALS.clientId }}
        password: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}

    - name: Build and push backend image
      run: |
        docker build -t acrk8svithu.azurecr.io/backend-app:${{ github.sha }} ./backend
        docker push acrk8svithu.azurecr.io/backend-app:${{ github.sha }}

    - name: Build and push frontend image
      run: |
        docker build -t acrk8svithu.azurecr.io/frontend-app:${{ github.sha }} ./frontend
        docker push acrk8svithu.azurecr.io/frontend-app:${{ github.sha }}

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Update backend deployment image
      run: |
        kubectl set image deployment/backend-deployment backend=acrk8svithu.azurecr.io/backend-app:${{ github.sha }}

    - name: Update frontend deployment image
      run: |
        kubectl set image deployment/frontend-deployment frontend=acrk8svithu.azurecr.io/frontend-app:${{ github.sha }}

    - name: Verify rollout status backend
      run: kubectl rollout status deployment/backend-deployment

    - name: Verify rollout status frontend
      run: kubectl rollout status deployment/frontend-deployment
